apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: log-anomaly
type: Opaque
data:
  mongo-root-username: YWRtaW4= # admin
  mongo-root-password: YWRtaW4= # admin
  mongo-initdb-database: bG9nc19kYg== # logs_db
